# Node.js Package

name: publish


on:
  push:
    branches:
      - beta
      - master
      - next

# 任务
jobs:

  # 任务 - build
  build:
    # 任务名称
    name: npm publish - ${{ matrix.os }} and ${{ matrix.node-version }}
    
    # 依赖任务
    # needs: build
    
    # 运行系统
    runs-on: ${{ matrix.os }}
    # runs-on: ubuntu-latest
      
    # 战略
    strategy:
      matrix:
        node-version: [12.x]
        os: [macOS-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '2627500295'
    
      - name: Install Dependencies
        run: npm install
      
      - name: npm publish from gpr (github package registry)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
        run: |
          yarn build
          yarn semantic-release
        
